version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    install:
      - pip install -r requirements.txt
    build:
      - sphinx-build -b html docs/source/ docs/build/html

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
